=head1 Installing Combust on Mandriva

Rough guide, kindly provided by a friend on the inside:

=head2 On Mandriva

Tried on Cooker - could work on earlier versions 

=head2 Check out combust:

    git clone git://git.develooper.com/combust.git combust

=head2 Check out content and setup tree
    
    cd combust
    svn co https://svn.perl.org/perl.org/docs/live perl.org-docs-live
    mkdir docs
    cd docs
    ln -s ../perl.org-docs-live live
    cd ..

=head2 Patch combust

Note - one needs to patch C<httpd2.tmpl> instead of C<httpd.tmpl>!

    diff --git a/apache/conf/httpd2.tmpl b/apache/conf/httpd2.tmpl
    index 7749416..bb35725 100644
    --- a/apache/conf/httpd2.tmpl
    +++ b/apache/conf/httpd2.tmpl
    @@ -6,9 +6,10 @@ PidFile             "[% config.log_path %]/httpd.pid"
     
     Listen              [% config.port %]
     
    -LoadModule perl_module [% apache_modules %]/mod_perl.so
    -LoadModule apreq_module [% apache_modules %]/mod_apreq2.so
    +LoadModule perl_module [% modperl_path %]
    +LoadModule apreq_module /usr/lib/apache-extramodules/mod_apreq2.so
     LoadModule log_config_module [% apache_modules %]/mod_log_config.so
    +LoadModule autoindex_module [% apache_modules %]/mod_autoindex.so
     LoadModule alias_module [% apache_modules %]/mod_alias.so
     LoadModule env_module [% apache_modules %]/mod_env.so
     LoadModule status_module [% apache_modules %]/mod_status.so

=head2 make config file

    cat > combust.conf <<EOF
    perl  = /usr/bin/perl
    httpd = /usr/sbin/httpd
    modperl_path = /usr/lib/apache-extramodules/mod_perl.so
    apache_libexec = /usr/lib/apache
    servername = combust.mydomain.com
    sites = www, dev
    port = 8225
    #external_port = 80
    apache_reload = 1 
    proxyip_forwarders = 127.0.0.1
    use_apache_statinc = 1
    [www]
    servername = www.mydomain.com
    aliases    = wwwperl.mydomain.com
    
    [dev]
    servername = dev.mydomain.com

    EOF

=head2 Setup nameservice

Edit C</etc/hosts> or setup DNS for the C<mydomain.com> addresses above.  If
you're just working on your local machine, you can set them to C<127.0.0.1>

=head2 Start the server

From the combust checkout dir:

    export CBROOT="$PWD" CBROOTLOCAL="$PWD"
    ./bin/run_httpd

( You will probably have perl errors in your C<logs/error_log> )

Now play "install all the CPAN dependencies":

=over 4

=item * Try installing Bundle::Combust

But it is probably out of date.

=item * Use urpmi / apt-get

Using apt-get:

    apt-get install libconfig-simple-perl libapache2-mod-perl2 \
     libapache2-mod-apreq2 libapache-dbi-perl libexception-class-perl \
     libcache-memcached-perl libcache-cache-perl \
     libapache2-request-perl 
    dh-make-perl libyahoo-search-perl

Using urpmi on Mandriva:
    
    urpmi perl-Config-Simple apache-mod_perl apache-mod_apreq  \
        perl-Apache-DBI perl-Exception-Class perl-Cache-Memcached \
        perl-Cache-Cache 'perl(Apache2::Request)'

    cpan2dist --verbose --format=CPANPLUS::Dist::Mdv --install \
        --timeout 0 Yahoo::Search

=back

=cut
