#!/usr/bin/perl

use strict;
use warnings;

use XML::LibXML;
# use YAML::XS;
use YAML;

my $parser = XML::LibXML->new();

my $opml = "subscriptions.opml";

if (! -e $opml)
{
    system("./fetch-opml");
}

my $doc = $parser->parse_file($opml);

my @tags = $doc->findnodes("//outline[\@title]");

my @feeds = 
    (map
        { 
            { 
                title => $_->getAttribute("title"),
                web => $_->getAttribute("htmlUrl"),
                url => $_->getAttribute("xmlUrl"),
            }
        }
        @tags
    );

open my $out, ">", "perlanetrc"
    or die "Could not open perlanetrc";
binmode $out, ":utf8";
print {$out} Dump(
    {
        title => "Perlsphere as Perlanet",
        description => "A Perlsphere clone using Perlanet",
        url => "http://www.shlomifish.org/perlsphers-using-perlanet/",
        author =>
        {
            name => "Shlomi Fish",
            email => 'shlomif@iglu.org.il',
        },
        entries => 20,
        opml => "opml.xml",
        page =>
        {
            file => "index.html",
            template => "index.tt",
        },
        feed => 
        {
            file => "atom.xml",
            format => "Atom",
        },
        feeds => \@feeds,
    }
);
close($out);
