#!/usr/bin/tclsh
package require Expect
# This script is adapted from:
# http://www.unix.com/shell-programming-scripting/46887-use-send-command-expect-package.html
# It is meant to dump the codes behind the keys generated by the commands.
# Accepts two arguments of a command line program.

#globals
exp_internal 1
log_user 0
set timeout 1000

if {[catch {spawn [lindex $argv 0] [lindex $argv 1]} err]} {
puts "$err during exec of [lindex $argv 0]"
exit
}

interact
