=head1 Installing Combust on Mandriva

Rough guide, kindly provided by a friend on the inside:

=head2 On Mandriva

Tried on Cooker - could work on earlier versions 

=head2 Check out combust:

    git clone git://git.develooper.com/combust.git combust

=head2 Check out content and setup tree
    
    cd combust
    svn co https://svn.perl.org/perl.org/docs/live perl.org-docs-live
    mkdir docs
    cd docs
    ln -s ../perl.org-docs-live live
    cd ..

=head2 Patch combust

    --- a/apache/conf/httpd2.tmpl
    +++ b/apache/conf/httpd2.tmpl
    @@ -11 +11,2 @@ LoadModule apreq_module [% apache_modules %]/mod_apreq2.so
    -LoadModule log_config_module [% apache_modules %]/mod_log_config.so
    +#LoadModule log_config_module [% apache_modules %]/mod_log_config.so
    +LoadModule autoindex_module [% apache_modules %]/mod_autoindex.so

=head2 make config file

    cat > combust.conf <<EOF
    perl  = /usr/bin/perl
    httpd = /usr/sbin/apache2
    modperl_path = /usr/lib/apache2/modules/mod_perl.so
    apache_libexec = /usr/lib/apache2/modules/
    servername = combust.mydomain.com
    sites = www, dev
    port = 8225
    #external_port = 80
    apache_reload = 1 
    proxyip_forwarders = 127.0.0.1
    use_apache_statinc = 1
    [www]
    servername = www.mydomain.com
    aliases    = wwwperl.mydomain.com
    
    [dev]
    servername = dev.mydomain.com

    EOF

=head2 Setup nameservice

Edit C</etc/hosts> or setup DNS for the C<mydomain.com> addresses above.  If
you're just working on your local machine, you can set them to C<127.0.0.1>

=head2 Start the server

From the combust checkout dir:

    export CBROOT=$PWD CBROOTLOCAL=$PWD
    bin/run_httpd

( You will probably have perl errors in your C<logs/error_log> )

Now play "install all the CPAN dependencies":

=over 4

=item * Try installing Bundle::Combust

But it is probably out of date.

=item * Use urpmi / apt-get

Using apt-get:

    apt-get install libconfig-simple-perl libapache2-mod-perl2 \
     libapache2-mod-apreq2 libapache-dbi-perl libexception-class-perl \
     libcache-memcached-perl libcache-cache-perl \
     libapache2-request-perl 
    dh-make-perl libyahoo-search-perl

Using urpmi
    
    urpmi perl-Config-Simple apache-mod_perl2 apache-
